//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 11:44:43 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jspasic.rs/soap/customerdetails", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rs.jspasic.webservice.soap.model;
