//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.08 at 08:44:35 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jspasic.rs/webservice/ates-web-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rs.jspasic.webservice.model;
